config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    
    registrations: 'users/registrations'
  }
  resources :users,only: [:show,:index,:edit,:update]
  resources :books do
  	resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end
#フォロー、フォロワー機能のルーティング
  resources :relationships, only: [:create, :destroy]

  root 'home#top'
  get 'home/about' => 'home#about'
  get 'users/follows/:id' => 'users#following',as:"follows_show"
  get 'users/followers/:id' => 'users#followers',as:"followers_show"

#検索機能
  get 'search' => 'search#search',as:'search'


end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :book_comments, dependent: :destroy
	has_many :favorites, dependent: :destroy

	def favorited_by?(user)
            favorites.where(user_id: user.id).exists?
    end



	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}


	def Book.search(search, user_or_book)
		if user_or_book == "2"
		  Book.where(['title LIKE ?', "%#{search}%"])
		else
		  Book.all
		end
    end

    def Book.search(search, user_or_book, how_search)
	    if how_search == "1"
	        Book.where(['title LIKE ?', "#{search}"])
	    elsif how_search == "2"
	        Book.where(['title LIKE ?', "#{search}%"])
	    elsif how_search == "3"
	        Book.where(['title LIKE ?', "%#{search}"])
	    elsif how_search == "4"
	        Book.where(['title LIKE ?', "%#{search}%"])
	    else
	        Post.all
	    end
    end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :correct_book, only: [:edit, :update]

  def show
  	@book = Book.find(params[:id])
    @new_book =Book.new
    @book_comment = BookComment.new
  end

  def index

    @book =Book.new

  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。

  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body, :user_id)
  end

  def correct_book
      book = Book.find(params[:id])
      unless book.user == current_user
      redirect_to books_path
      end
  end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_comment.html.erb
<h3>コメント一覧</h3>

<% book_comments.each do |book_comment| %>
    <div class=<%= 'comment' + book_comment.id.to_s %> >
    	name:<%= book_comment.user.name %>

	  	day:<%= book_comment.created_at.strftime('%Y/%m/%d') %>

		comment:<%= book_comment.comment %>

	    <% unless current_user != book_comment.user %>
			<%= link_to "削除",  book_book_comment_path(book_comment.book.id,book_comment.id), method: :delete, remote: true %>
		<% end %>
    </div>

<% end %>


app/views/books/_comment_book.html.erb
<h3>コメント入力</h3>
<%= form_with(model: [@book, @book_comment], remote: true ) do |f| %>
<%= f.text_area :comment %>
<%= f.submit "送信" %>
<% end %>

app/views/books/_favorite.html.erb
<% if book.favorited_by?(current_user) %>
				      
	
		<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
		<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
		いいね数：<span class="glyphicon glyphicon-heart"><%= book.favorites.count%></span>


	<% end %>
	
<% else %>

	
		<%= link_to book_favorites_path(book), method: :post, remote: true do %>
		<i class="fa fa-heart-o" aria-hidden="true"></i>
	いいね数：<span class="glyphicon glyphicon-heart-empty"><%= book.favorites.count %> </span>
	<% end %>
	
<% end %>

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
	<div class="row">
	<div class="col-md-6 col-md-offset-3">

	<h1>Editing Book</h1>
	
	<% if @book.errors.any? %>
        <div id="error_explanation">
          <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
          <ul>
           <% @book.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
           <% end %>
          </ul>
        </div>
    <% end %>

	<%= render "books/newform", book: @book %>
	<%= link_to "Show", @book, class: "book_#{@book.id}" %>
	<%= link_to "Back", books_path, class: "back" %>

	</div>
	<div class="col-md-3"></div>

	</div>
</div>

app/views/books/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>
			<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>

		</div>

		<div class="col-xs-9">
			<h2>Books index</h2>
			<!--books一覧 -->
			<table class="table table-hover table-inverse">
				<thead>
					<tr>
						<th></th>
						<th>Title</th>
						<th>Opinion</th>
						<th colspan="3"></th>
					</tr>
				</thead>

				<tbody>
					<% @books.each do |book| %>
					<tr>
						<td>
							<%= link_to(book.user) do %>
							<%= attachment_image_tag(book.user, :profile_image, fallback: "no-image-mini.jpg", size: "100x100") %>
							<% end %>
						</td>
						<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>
						<td><%= link_to "コメント数:#{book.book_comments.count} ", book_path(book.id) %></td>
                         <!--いいね部分テンプレート-->
						 <td id="favorite_buttons_<%= book.id%>"><%= render 'books/favorite', book: book %></td>

					</tr>
					<% end %>

				</tbody>
			</table>

			<% if @book.errors.any? %>
        <div id="error_explanation">
          <h3><%= @book.errors.count %>errors prohibited this book from being saved:</h3>
          <ul>
           <% @book.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
           <% end %>
          </ul>
        </div>
      <% end %>

			<!--books一覧 -->


		</div>
	</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
		
		<% if notice %>
    　<p><%= notice %></p>
    <% end %>
    <% if alert %>
       <p><%= alert %></p>
    <% end %>
		<div class="col-xs-3">

			<h2>User info</h2>
			<%= render 'users/profile', user: current_user %>

			<h2>New book</h2>
			<%= render 'books/newform', book: @new_book %>

		</div>

		<div class="col-xs-9">
			<h2>Book detail</h2>

			<table class="table">
					<tr>
						<td>
							<%= link_to (@book.user) do %>
							<%= attachment_image_tag(@book.user, :profile_image, fallback: "no-image-mini.jpg", size: "100x100") %><br>
							<%= @book.user.name %>
							<% end %>
						</td>
						<td><%= link_to @book.title, @book %></td>
						<td><%= @book.body %></td>
						<td>コメント数:<%= @book.book_comments.count %></td>

				        <!--いいね部分テンプレート-->
                        <td id="favorite_buttons_<%= @book.id%>"><%= render 'books/favorite', book: @book %></td>

						    


					<% if @book.user == current_user %>
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
					<% end %>
					</tr>
			</table>


              
            <div class="comments"><%= render 'books/comment', book_comments: @book.book_comments %></div>
            <!-- <td class="comment_form"><%= render 'books/comment_book', book: @book %></td> -->

            <h3>コメント入力</h3>
<%= form_with(model: [@book, @book_comment], remote: true ) do |f| %>
<%= f.text_area :comment %>
<%= f.submit "送信" %>
<% end %>

           
				  		



		</div>
	</div>
</div>